title      : Prof. Qi Lü
lang       : en
description:  School of Mathematics, Sichuan University, China.
copyright  : © 2018 - 2020 lvqi.github.io All Rights Reserved

nav:
 - name: Home
   link: /
 - name: Publications
   link: /pages/Publication.html
 - name: Honors
   link: /pages/Honors.html
 - name: Editorial Board
   link: /pages/Editorial-Board.html